MSMVV-11/loggingremoved
xenit-eu/care4alf pull request #14
Opened 2024-02-21 15:03 UTC by pvriel

https://xenitsupport.jira.com/browse/MSMVV-11

- updated DE version to the latest one;
- Node.JS gradle plugin bug fix ('ivy.xml not found') -> c4a-impl/build.gradle;
- removed Log4J imports (since this was causing a bug with Alfresco 7.4) --> removed logging module all together from care4alf;
- the integration tests did not work for me at all -> fixed c4a-test/build.gradle & c4a-test/7x/overrides.gradle

2024-02-21 15:42 UTC, pvriel commented
Also, Github Actions bug fix (by removing all Harbor references).

2024-02-22 08:13 UTC, WimCrols commented
The build could also benefit from a test report plugin (see https://github.com/xenit-eu/alfred-api/blob/master/.github/workflows/ci.yml#L72 ), but since we are sunsetting this, you don't have to.

2024-02-22 08:14 UTC, WimCrols requested changes
Please update README with clear end-of-life info, indicating 7.4 will be the latest supported version. You can also link to OOTB support tools.

2024-02-26 14:41 UTC, pvriel commented
@WimCrols like this (new commit)?

2024-02-26 15:14 UTC, WimCrols requested changes

2024-02-26 15:14 UTC, WimCrols commented on README.md
> +## Important note regarding Care4Alf
(non-blocking) `Important note` is enough IMHO. Since the README is in the care4alf repo, the fact that is about care4alf is sufficiently implied.

2024-02-26 15:14 UTC, WimCrols commented on README.md
> +Please be aware that while Care4Alf version 4.0.0 introduces support for Alfresco 7.4, it will no longer offer compatibility with earlier Alfresco versions such as 6.0, 6.1, 7.0, 7.1, and 7.2.
Could you list the supported Alfresco version? Otherwise people needs to go over previous release to see if their Alfresco is supported.

2024-02-26 15:14 UTC, WimCrols commented
> @WimCrols like this (new commit)?

Thanks! I added my remarks inline.

2024-02-27 08:25 UTC, pvriel commented
@WimCrols like this? ;)

2024-02-27 09:44 UTC, WimCrols approved these changes
:shipit:

2024-02-27 10:40 UTC, merged